version: '3.9'
services:
    dumbdrop:
        image: dumbwareio/dumbdrop:latest
        ports:
            - "7608:3000"
        volumes:
            - "${APP_DATA_DIR}/local_uploads:/app/uploads"
        environment:
            DUMBDROP_PIN: 123456
#           - MAX_FILE_SIZE=2048
        
