version: '3.5'

services:
  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jakubmedia
    volumes:
      - "${APP_DATA_DIR}/psql_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  psql_data:
